trigger:
  - main

parameters:
  - name: azureSubscription
    type: string
    default: MyARMSubscription

variables:
  - group: web-app-variables

  - name: buildConfiguration
    value: 'Release'
  
  - name: releaseBranchName
    value: 'release'

stages:
  - stage: Deploy_Build
    displayName: 'Build the web application'
    jobs: 
      - template: templates/templates-deploy-with-env/azure-pipelines-templates-build.yml
              
  - stage: Deploy_Dev
    displayName: Deploy to the dev environment
    dependsOn: Deploy_Build
    jobs:
      - template: templates/templates-deploy-with-env/azure-pipelines-templates.yml
        parameters:
          env: dev
          azureSubscription: MyARMSubscription
          appServiceName: $(WebAppNameDev)
          package: $(Pipeline.WorkSpace)/drop/

  - stage: Deploy_Staging
    displayName: Deploy to the staging environment
    dependsOn: Deploy_Dev
    jobs:
      - template: templates/templates-deploy-with-env/azure-pipelines-templates.yml
        parameters:
          env: staging
          azureSubscription: MyARMSubscription
          appServiceName: $(WebAppNameStaging)
          package: $(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip