jobs:
  - deployment: Deploy
    variables:
      webAppType: webAppLinux

    condition: succeeded()
    pool: 
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.env }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              displayName: 'Azure App Service Deploy to ${{ parameters.env }} environment'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appName: ${{ parameters.appServiceName }}
                appType: $(webAppType)
                package: ${{ parameters.package }}